name: gif_share_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  cached_network_image: ^3.2.2
  cross_file: ^0.3.3+2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3
  share_plus_platform_interface: ^3.2.0
  very_good_analysis: ^3.1.0
